xset r rate 120 90
redshift -O 3000 -P

# endgame
# doas setxkbmap -variant dvorak

shred ~/.bash_history*
rm -f ~/.bash_history*
rm -f ~/acme.dump*
rm -f ~/\#\**

unclutter -idle 1 -b

# xgifwallpaper ~/.config/wallpapers/lain_wired.gif &

# adding this because of retards
systemctl --user set-environment DISPLAY=:0

feh --bg-fill ~/.config/wallpapers/flowers.jpg
picom &

exec enforcer > /tmp/enforcer.log
# exec dwm
# exec wmaker
