xset r rate 120 90
redshift -O 3000 -P

# endgame
# doas setxkbmap -variant dvorak

rm ~/.bash_history*

unclutter -idle 1 -b

# xgifwallpaper ~/.config/wallpapers/lain_wired.gif &

feh --bg-fill ~/.config/wallpapers/cicada7.jpg
picom &
exec enforcer > /tmp/enforcer.log
