# declare-option str black 'rgb:000000'
# declare-option str menu 'rgb:222222'
# set-face global MenuBackground "default,%opt{menu}"

colorscheme mygruvbox

# other aesthetic options
set-option global tabstop 4
set-option global scrolloff 4,8

# use editorconfig
hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* editorconfig-load

# clipboard ( now works on the default clipboard! )
map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -ib<ret>"
map -docstring "paste the clipboard" global user p "<a-!> xsel -ob<ret>"

# indentation with spaces
hook global InsertChar \t %{ try %{
    execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}
hook global InsertDelete ' ' %{ try %{
    execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}

# plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload
plug "kakoune-lsp/kakoune-lsp" noload
plug "niljimeno/yazi.kak"
plug "niljimeno/qmake.kak"
plug "niljimeno/compile.kak"
plug "alexherbo2/auto-pairs.kak"

enable-auto-pairs

plug "andreyorst/fzf.kak" config %{
  map global normal <c-p> ': fzf-mode<ret>'
} defer <module-name> %{
  # settings of module
}

hook global NormalKey <c-a> %{ try %{
    execute-keys 'bi<lt><esc>heya<gt><lt>/<esc>pa<gt><esc><a-f><lt>;<esc>'
}}

hook global InsertKey <c-a> %{ try %{
    execute-keys '<esc>bi<lt><esc>heya<gt><lt>/<esc>pa<gt><esc><a-f><lt>;i'
}}


# lsp
eval %sh{kak-lsp}
lsp-enable

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'
map global normal <c-l> ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

map global user a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global user <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global user f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global user t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global user d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global user D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

map global normal <a-y> ':yazi-root<ret>'
map global normal <c-y> ':yazi<ret>'
map global normal <c-k> ':db<ret>'


hook global WinSetOption filetype=gleam %{
    require-module gleam
}

hook -group lsp-filetype-gleam global BufSetOption filetype=gleam %{
    set-option buffer lsp_servers %{
        [gleam]
        filetypes = ["gleam"]
        root_globs = ["gleam.toml", "manifest.toml"]
        command = "/usr/bin/gleam"
        args = ["lsp"]
    }
}

hook -group lsp-filetype-csharp global BufSetOption filetype=csharp %{
    set-option buffer lsp_servers %{
        [csharp]
        filetypes = ["csharp"]
        root_globs = [".csproj", "app.manifest"]
        command = "/usr/bin/csharp-ls"
    }
}

# autoformat on save
hook global BufSetOption filetype=(clojure|go) %{
    hook buffer BufWritePre .* lsp-formatting-sync
}

# open a new terminal window
map global normal <c-e> ':terminal sh<ret>'

map -docstring "Compile (prompted)" \
    global normal <a-r> ':compile<ret>'

map -docstring "Compile (no prompts)" \
    global normal <c-r> ':compile-quick<ret>'


# multiple windows
define-command split %{
    new edit %sh{ echo "$kak_buffile" }
}
map global normal <c-w> ':split<ret>'
map global insert <c-w> '<esc>:split<ret>i'


plug "eraserhd/parinfer-rust" config %{
    hook global WinSetOption filetype=(clojure|lisp|picolisp|racket|scheme) %{
        parinfer-enable-window -smart
    }
}
source "%val{config}/csharp.kak"
source "%val{config}/idris.kak"
